version: '3.4'

services:
  buses:
    image: buses
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8888:5000
    restart: "unless-stopped"
    volumes:
      - db:/opt/buses/web/data

volumes:
  db:

