---
swagger: "2.0"
info:
  description: Buses
  version: 0.0.1
  title: Buses
  contact:
    email: almiluk@psu.ru
basePath: /
schemes:
- https
paths:
  /login:
    get:
      responses:
        "200":
          description: "Get page for logging in"
        "500":
          description: "Server error"
    post:
      parameters:
      - name: login
        in: body
        required: true
        schema:
          $ref: "#/definitions/logginData"
      responses:
        "200":
          description: "Logged in"
        "404":
          description: "Cannot find user"
        "500":
          description: "Server error"
      consumes:
        - "multipart/form-data"
      produces:
        - "text/html"
  /registration:
    get:
      responses:
        "200":
          description: "Get page for logging in"
        "500":
          description: "Server error"
    post:
      parameters:
      - name: login
        in: body
        required: true
        schema: 
          $ref: "#/definitions/regData"
      responses:
        "201":
          description: "User created"
        "400":
          description: "Cannot create such user"
        "500":
          description: "Server error"
      consumes:
        - "multipart/form-data"
      produces:
        - "text/html"
definitions:
  regData:
    type: "object"
    properties:
      login:
        type: "string"
      password:
        type: "string"
      rep_password:
        type: "string"
  logginData:
    type: "object"
    properties:
      login:
        type: "string"
      password:
        type: "string"

