---
swagger: "2.0"
info:
  description: Buses
  version: 0.0.1
  title: Buses
  contact:
    email: almiluk@psu.ru
basePath: /
schemes:
- https
paths:
  /:
    get:
      responses:
        "302":
          description: "Redirect to route search page"
        "500":
          description: "Server error"
      produces:
        - "text/html"
      operationId: handlers.index
  /login:
    get:
      responses:
        "200":
          description: "Get page for logging in"
        "500":
          description: "Server error"
      produces:
        - "text/html"
      operationId: handlers.login_page
    post:
      parameters:
      - name: login_data
        in: body
        required: true
        schema:
          $ref: "#/definitions/logginData"
      responses:
        "200":
          description: "Logged in"
        "404":
          description: "Cannot find user"
        "500":
          description: "Server error"
      consumes:
        - "application/x-www-form-urlencoded"
      produces:
        - "text/html"
      operationId: handlers.login_user
  /registration:
    get:
      responses:
        "200":
          description: "Get page for logging in"
        "500":
          description: "Server error"
      produces:
        - "text/html"
      operationId: handlers.registration_page
    post:
      parameters:
      - name: reg_data
        in: body
        required: true
        schema: 
          $ref: "#/definitions/regData"
      responses:
        "201":
          description: "User created"
        "400":
          description: "Cannot create such user"
        "500":
          description: "Server error"
      consumes:
        - "application/x-www-form-urlencoded"
      produces:
        - "text/html"
      operationId: handlers.registrate_user
  /routes:
    get:
      responses:
        "200":
          description: "Get page for searching routes"
        "500":
          description: "Server error"
      produces:
        - "text/html"
      operationId: handlers.routes_page
    post:
      parameters:
      - name: route_data
        in: body
        required: true
        schema:
          $ref: "#/definitions/routeData"
      responses:
        "200":
          description: "Page with a list of routes"
        "400":
          description: "Bad request"
        "500":
          description: "Server error"
      consumes:
        - "application/x-www-form-urlencoded"
      produces:
        - "text/html"
      operationId: handlers.find_routes
definitions:
  regData:
    type: "object"
    properties:
      login:
        type: "array"
        maxItems: 1
        items:
          type: "string"
      password:
        type: "array"
        maxItems: 1
        items:
          type: "string"
          format: "password"
      rep_password:
        type: "array"
        maxItems: 1
        items:
          type: "string"
  logginData:
    type: "object"
    properties:
      login:
        type: "array"
        maxItems: 1
        items:
          type: "string"
      password:
        type: "array"
        maxItems: 1
        items:
          type: "string"
          format: "password"
  routeData:
    type: "object"
    properties:
      departure_stop_id:
        type: "array"
        maxItems: 1
        items:
          type: "string"
      arrival_stop_id:
        type: "array"
        maxItems: 1
        items:
          type: "string"
          format: "password"
