name: Deploy PR state to the server for testing

on:
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Perform the deployment
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: |
            [ -d pr/${{ github.event.pull_request.number }} ] || git clone git@github.com:teamdevm/team-project-buses.git pr/${{ github.event.pull_request.number }}
            git -C pr/${{ github.event.pull_request.number }} fetch
            git -C pr/${{ github.event.pull_request.number }} checkout ${{ github.head_ref }}
            cp bus/web/data/buses.db pr/${{ github.event.pull_request.number }}/web/data/buses.db
            cd pr/${{ github.event.pull_request.number }}/web
            python3 init_db.py

